### ISSUE TITLE
Issue in Production when trying to launch VF Calendar Page

### ISSUE THREAD

**Issue by pawelforce77** [msrivastav13/Bootstrap_Resposive_Calendar#1]
12:29:35.470 (470430279)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

Class.ResponsiveCalendarCtrl.getCalendarItems: line 22, column 1
12:29:35.470 (470475125)|CODE_UNIT_FINISHED|VFRemote: ResponsiveCalendarCtrl invoke(getCalendarItems)
12:29:35.471 (471875041)|EXECUTION_FINISHED

**Comment by msrivastav13** [comment]
@pawelforce77 The solution has been provided with null checks added .Thanks!

**Comment by pawelforce77** [comment]
Thank you Mohith.
