### ISSUE TITLE
Apex CPU time limit exceeded

### ISSUE THREAD

**Issue by pawelforce77** [msrivastav13/Bootstrap_Resposive_Calendar#2]
Received the Error while testing, following is excerpt from debug log:
15:58:37.374 (21374265653)|FATAL_ERROR|System.LimitException: Apex CPU time limit exceeded
Class.ResponsiveCalendarCtrl.getCalendarItems: line 21, column 1
15:58:37.374 (21374310610)|CODE_UNIT_FINISHED|VFRemote: ResponsiveCalendarCtrl invoke(getCalendarItems)
15:58:37.376 (21376309904)|EXECUTION_FINISHED

Followed by auto generated email : 
Operation: /apexremote
By user/organization: 005a000000AfIyI/00D30000000mTln
Caused the following Apex resource warnings:
Number of query rows: 50001 out of 50000
Maximum heap size: 5815191 out of 6000000
(these emails can be disabled from the user detail page for this user)

**Comment by msrivastav13** [comment]
@pawelforce77 The fix is been provided .Basically limiting to show recent data on calendar due to force.com query limits .Thanks

**Comment by pawelforce77** [comment]
Thank you for the fix! All is working wonderfully :)
