### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by pawelforce77** [msrivastav13/Bootstrap_Resposive_Calendar#3]
Hi,
I'm interested to see if there a way to pull and display data only for a specific User or a User that initiates a quarry? 
Thank you in advance for consideration.

**Comment by msrivastav13** [comment]
@pawelforce77 Please see the new branch .I have added ownerId filter for you .Please note use this if you explicitly need to filter by ownerId and I assume your object has ownerId field .If not do let me know whats your object owner field and I can add that .Thanks

**Comment by msrivastav13** [comment]
https://github.com/msrivastav13/Bootstrap_Resposive_Calendar/blob/ExplicitFilterLoggedInUser/src/classes/ResponsiveCalendarCtrl.cls

@pawelforce77 Here is the code

**Comment by pawelforce77** [comment]
Hi, It does not seem to be working. I'm getting this, from deubg log, :
17:11:35.024 (24249845)|EXCEPTION_THROWN|[19]|System.QueryException: unexpected token: =
17:11:35.024 (24338717)|SYSTEM_MODE_EXIT|false
17:11:35.024 (24400898)|FATAL_ERROR|System.QueryException: unexpected token: =

Class.ResponsiveCalendarCtrl.getCalendarItems: line 19, column 1
17:11:35.024 (24443102)|CODE_UNIT_FINISHED|VFRemote: ResponsiveCalendarCtrl invoke(getCalendarItems)
17:11:35.027 (27811391)|EXECUTION_FINISHED

**Comment by pawelforce77** [comment]
I tried modifying it like so but received same error
querystr=querystr+' from '+ObjectName+'where OwnerId= :UserInfo.getUserID()'+' order by createdDate DESC limit 25000';//Limit the data

**Comment by msrivastav13** [comment]
@pawelforce77 Just corrected the code .It had little glitch

https://github.com/msrivastav13/Bootstrap_Resposive_Calendar/commit/786ce9dc66abd443cbc8b6c9e51ab0858044ecc7

Please use the updated code .

**Comment by pawelforce77** [comment]
Thank you for the correction. I appreciate your help. Finished all testing and works as was requested.
