### ISSUE TITLE
Feature Request - Events to Appointments

### ISSUE THREAD

**Issue by pawelforce77** [msrivastav13/Bootstrap_Resposive_Calendar#4]
Events to Appointments

My org has renamed Events to Appointments to accommodate specific business purpose.
Would love to be able to reflect that correctly in the app, wherever it has label Events to change it to Appointments.
Thank you in advance for your consideration of this.

**Comment by msrivastav13** [comment]
@pawelforce77 The new package with this feature is below

https://login.salesforce.com/packaging/installPackage.apexp?p0=04t90000000FUlx

This is completely new package and you may try this in sandbox first before overriding .Basically there is lot of change in static resource which means it requires you a complete new package .

Please close this issue if it works .Thanks

**Comment by pawelforce77** [comment]
Hi, Thank you very much for the update. I will load it into the sandbox and test it out.

**Comment by pawelforce77** [comment]
Thank you! All set, appreciate the new package.
